---
output: html_document
---

# MCF202 Análisis estadísticos
## Actividad 1: Manipulación de datos en R

_Dr. Marco Aurelio González Tagle_ 

05/08/2014

-------------------


## Actividades a realizar

Los datos climaticos de la regió boscosa  de Cumbres en Nuevo León fueron obtenidas para el día 18/05/2014 desde las 17:00hrs en intervalos de 10 min. hasta el día 19/05/2014 hasta las 13:30 horas. 

Los datos provienen del [Sistema Meteorológico Nacional](http://smn.cna.gob.mx/emas/), los datos de la estación provienen del siguintes link: [Estación Cumbres de MTY I](http://smn.cna.gob.mx/emas/txt/NL10_10M.TXT). La base de datos se encuentra disponible en el blog [Blog mgtagle/base de datos](http://wp.me/p145K0-7s)

1. Importar las bases de datos de clima **Cumbres.csv** a R
```{r importar}
setwd("/Volumes/TOSHIBA/Rstudio/Principios_estadistica/Data")
cumbres <-read.csv("Cumbres.csv")
```

Los nombres de las variables son los siguientes: `r names(cumbres)` y su significado se encuentra abajo

```
Las variables que se van a manejar son: 
TEMPCOMB: Temperatura combustibles forestales
HUMCOMB: Humedad de los combustibles forestales
TEMP: Temperatura
HR: Humedad relativa
```

### Conteste las siguientes preguntas:

1. Determinar la media aritmética para cada una de las variables medidas:
  * Cual es la media de la variable **TEMPCOMB**: `r mean(cumbres$TEMPCOMB)`
  * Cual es la media de la variable **HUMCOMB**: `r mean(cumbres$HUMCOMB)`
  * Cual es la media de la variable **TEMP**: `r mean(cumbres$TEMP)`
  * Cual es la media de la variable **HR**: `r mean(cumbres$HR)`


### Conteste las siguientes preguntas:

1. Determinar la desviación estándar para cada una de las variables medidas:
  * Cual es la media de la variable **TEMPCOMB**: `r sd(cumbres$TEMPCOMB)`
  * Cual es la media de la variable **HUMCOMB**: `r sd(cumbres$HUMCOMB)`
  * Cual es la media de la variable **TEMP**: `r sd(cumbres$TEMP)`
  * Cual es la media de la variable **HR**: `r sd(cumbres$HR)`

### Conteste las siguientes preguntas:
1. Determinar 
 * Cuantos datos de **TEMPCOMB** tienen son iguales o mayores a la media de  **TEMPCOMB**:
 * Cuantos datos de **HR** tienen son iguales o menores a la media de  **HR**:


### Realizar muestras

Con la base de datos, realizar una submuestra `(subset)` de la siguiente manera:

1. Determinar un subconjunto con los datos de **TEMPCOMB** menores a la media y detrminar los siguientes puntos:
  * Cual es la media de la variable
  * Cual es la desviación estándar de la variable:
  
2. Determinar un subconjunto con los datos de **HUMCOMB** menores a la media y detrminar los siguientes puntos:
  * Cual es la media de la variable
  * Cual es la desviación estándar de la variable:


Con la base de datos original, realizar una submuestra `(subset)` con las siguientes restriciones:
  * __DIRR__ Dirección de las rafagas de viento mayores a 100
  * __VELR__ Velociddad de las rafagas de viento mayores a 40 & con Dirección de viento __DIRR__ mayor a 150

## Entrega a Evernote 
Para registrar su Practica 1 exitosamente en **evernote** favor de seguir las siguientes instrucciones:
En el Asunto del email se debe incluir su nombre, número de matrícula seguido de las siguient indicacion: @Actividad1 

**Ejemplo: Marco A. González Tagle Matricula 1213458 @Actividad1**
